### ISSUE TITLE
bug: files not accessible inside binary

### ISSUE THREAD

**Issue by nonstdout** [mandarineorg/leaf#11]
It appears that files are not being added to the compiled binary.

## Folder structure

build/index.html
build/bundle.js
mod.ts
leaf.ts

## Config 

leaf.ts
```js
import { Leaf } from "./deps.ts";

Leaf.compile({
  modulePath: "./mod.ts",
  contentFolders: ["./build"],
  flags: ["--allow-all", "--unstable"]
})
```

mod.ts
```js
import { Application, send, Router } from "./deps.ts";
import { Leaf } from "./deps.ts";
const index = Leaf.readTextFileSync("./build/index.html")
const bundle = Leaf.readTextFileSync("./build/bundle.js")
const router = new Router();
router
.get("/", (context) => {
  context.response.body = index;
})
.get("/bundle.js", (context) => {
  context.response.headers.set("Content-Type", "application/javascript; charset=utf-8")
  context.response.body = bundle;
})
const app = new Application();
app.use(router.routes());
app.use(router.allowedMethods());
app.addEventListener("error", (evt) => {
  // Will log the thrown error to the console.
  console.log(evt.error);
});


console.log(`Listening on http://localhost:8000`);
await app.listen({ port: 8000 });

```

## Command to produce binary

```shell
deno run -A --no-check --unstable leaf.ts
```

## Outputted binary
```shell
./mod
```

## Results
Binary can be executed with `./mod` and it works if run from the same directory it was emitted to. However if it is moved anywhere else you receieve the below error.

```shell
error: Error: File not found (./build/index.html).
    at Function.registerOrGetFile (file://$deno$/bundle.js:22125:23)
    at Function.readFileSync (file://$deno$/bundle.js:22200:21)
    at Function.readTextFileSync (file://$deno$/bundle.js:22206:40)
    at file://$deno$/bundle.js:22295:20
```

**Comment by andreespirela** [comment]
@nonstdout Should be fixed in new version.
